- hosts: localhost
  vars:
    - packages:
      - vim
      - tmux
      - bind-utils
      - net-tools
      - xorg-x11-xauth
      - xorg-x11-apps
      - xorg-x11-utils
      - xorg-x11-fonts-Type1
      - unzip
      - smartmontools
      - compat-libcap1
      - libstdc++-devel
      - sysstat
      - gcc-c++
      - ksh
      - libaio-devel
    - oracle_base: /u01/app/oracle
    - oracle_inventory: /u01/app/oraInventory 
    - oracle_home: /u01/app/oracle/product/12.1.2/

  tasks:
    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Install all updates
      package:
        name: '*'
        state: latest

    - name: Install epel repo
      package:
        name: epel-release
        state: present

    - name: Install packages
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"

    - name: Ensure that X11 forwarding is enabled
      lineinfile: 
        line: "{{ item }}"
        path: /etc/ssh/sshd_config
      with_items:
        - 'X11Forwarding yes'
        - 'X11DisplayOffset 10'
      notify: Restart SSH

    - name: Create Oracle group
      group:
        name: oinstall
        state: present

    - name: Create Oracle user
      user:
        name: oracle
        group: oinstall
        state: present

    - name: Create Oracle Xauth file
      file:
        path: /home/oracle/.Xauthority
        state: touch
        owner: oracle
        group: oinstall

    - name: Add oracle bash profile
      copy:
        src: oracle_bash_profile
        dest: /home/oracle/.bash_profile

    # - name: Check if Oracle is already installed

    - name: Install cvuqdisk
      yum:
        name: ./files/database/rpm/cvuqdisk-1.0.10-1.rpm
        state: present

    - name: Set cvuqdisk environment variables
      lineinfile:
        line: 'CVUQDISK_GRP=oinstall'
        path: /etc/environment

    - name: Mount tmpfs with RW and Execute
      mount:
        path: /dev/shm
        src: tmpfs
        fstype: tmpfs
        opts: rw,exec
        state: present

    - name: Transfer THP disable script
      copy:
        src: files/disable-thp.service
        dest: /etc/systemd/system/disable-thp.service

    - name: Start thp-disable
      systemd:
        daemon_reload: true
        name: disable-thp
        state: started
        enabled: yes

    - name: Create tuned THP disable directory
      file:
        path: /etc/tuned/no-thp
        state: directory
    
    - name: Add tuned script
      copy: 
        src: files/tuned.conf
        dest: /etc/tuned/no-thp/tuned.conf
      notify: Update tuned profile

    - name: Increase limits to Oracle required values
      lineinfile:
        path: /etc/security/limits.conf
        line: "{{ item }}"
      with_items:
        - oracle  hard  nofile  65536
        - oracle  hard  nproc  16384
        - oracle  hard  nproc  16384
        - oracle  soft  stack  10240
        - oracle  hard  stack  32768

    - name: Add Oracle kernel parameters
      copy:
        src: 97-oracle-database-sysctl.conf
        dest: /etc/sysctl.d/97-oracle-database-sysctl.conf

    - name: Create Oracle directories
      file:
        path: "{{ item }}"
        state: directory
        recurse: yes
        owner: oracle
        group: oinstall
      with_items:
        - "{{ oracle_base }}"
        - "{{ oracle_inventory }}"
        - "{{ oracle_home }}"

    - name: Ensure that Oracle "mountpoints" exist
      file:
        path: "/{{ 'u%02x' | format(item) }}/oradata"
        state: directory
        recurse: yes
        owner: oracle
        group: oinstall
      loop: "{{ range(1,7,1) | list }}"

    - name: Copy database response file to an accessible location
      copy:
        src: db.rsp
        dest: /home/oracle/db.rsp

    - name: Run the Oracle installer silently
      shell: ./files/database/runInstaller -silent -waitForCompletion -noconfig -responseFile /home/oracle/db.rsp
      become: yes
      become_user: oracle

    - name: Run post install scripts
      shell: "{{ item }}"
      with_items:
        - /u01/app/oraInventory/orainstRoot.sh
        - /u01/app/oracle/product/12.2.0/dbhome_1/root.sh

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted

    - name: Update tuned profile
      shell: tuned-adm profile no-thp