insert into state(description,statecode) values('ALABAMA','AL');
insert into state(description,statecode) values('ALASKA','AK');
insert into state(description,statecode) values('AMERICAN SAMOA','AS');
insert into state(description,statecode) values('ARIZONA','AZ');
insert into state(description,statecode) values('ARKANSAS','AR');
insert into state(description,statecode) values('CALIFORNIA','CA');
insert into state(description,statecode) values('COLORADO','CO');
insert into state(description,statecode) values('CONNECTICUT','CT');
insert into state(description,statecode) values('DELAWARE','DE');
insert into state(description,statecode) values('DISTRICT OF COLUMBIA','DC');
insert into state(description,statecode) values('FEDERATED STATES OF MICRONESIA','FM');
insert into state(description,statecode) values('FLORIDA','FL');
insert into state(description,statecode) values('GEORGIA','GA');
insert into state(description,statecode) values('GUAM','GU');
insert into state(description,statecode) values('HAWAII','HI');
insert into state(description,statecode) values('IDAHO','ID');
insert into state(description,statecode) values('ILLINOIS','IL');
insert into state(description,statecode) values('INDIANA','IN');
insert into state(description,statecode) values('IOWA','IA');
insert into state(description,statecode) values('KANSAS','KS');
insert into state(description,statecode) values('KENTUCKY','KY');
insert into state(description,statecode) values('LOUISIANA','LA');
insert into state(description,statecode) values('MAINE','ME');
insert into state(description,statecode) values('MARSHALL ISLANDS','MH');
insert into state(description,statecode) values('MARYLAND','MD');
insert into state(description,statecode) values('MASSACHUSETTS','MA');
insert into state(description,statecode) values('MICHIGAN','MI');
insert into state(description,statecode) values('MINNESOTA','MN');
insert into state(description,statecode) values('MISSISSIPPI','MS');
insert into state(description,statecode) values('MISSOURI','MO');
insert into state(description,statecode) values('MONTANA','MT');
insert into state(description,statecode) values('NEBRASKA','NE');
insert into state(description,statecode) values('NEVADA','NV');
insert into state(description,statecode) values('NEW HAMPSHIRE','NH');
insert into state(description,statecode) values('NEW JERSEY','NJ');
insert into state(description,statecode) values('NEW MEXICO','NM');
insert into state(description,statecode) values('NEW YORK','NY');
insert into state(description,statecode) values('NORTH CAROLINA','NC');
insert into state(description,statecode) values('NORTH DAKOTA','ND');
insert into state(description,statecode) values('NORTHERN MARIANA ISLANDS','MP');
insert into state(description,statecode) values('OHIO','OH');
insert into state(description,statecode) values('OKLAHOMA','OK');
insert into state(description,statecode) values('OREGON','OR');
insert into state(description,statecode) values('PALAU','PW');
insert into state(description,statecode) values('PENNSYLVANIA','PA');
insert into state(description,statecode) values('PUERTO RICO','PR');
insert into state(description,statecode) values('RHODE ISLAND','RI');
insert into state(description,statecode) values('SOUTH CAROLINA','SC');
insert into state(description,statecode) values('SOUTH DAKOTA','SD');
insert into state(description,statecode) values('TENNESSEE','TN');
insert into state(description,statecode) values('TEXAS','TX');
insert into state(description,statecode) values('UTAH','UT');
insert into state(description,statecode) values('VERMONT','VT');
insert into state(description,statecode) values('VIRGIN ISLANDS','VI');
insert into state(description,statecode) values('VIRGINIA','VA');
insert into state(description,statecode) values('WASHINGTON','WA');
insert into state(description,statecode) values('WEST VIRGINIA','WV');
insert into state(description,statecode) values('WISCONSIN','WI');
insert into state(description,statecode) values('WYOMING','WY');

